image: ghcr.io/xyrisos/xyris-build/xyris-build:3.5.0
aliases:
    # Building
    build: scons
    debug: scons kernel-debug
    release: scons kernel-release
    # Testing
    test:
      script:
        - scons tests
        - ./Distribution/Tests/tests
    # Cleaning
    clean: scons -c
    test-clean: scons -c tests
    # Documentation
    docs:
      script: make docs
