image: ghcr.io/xyrisos/xyris-build/xyris-build:3.5.0
aliases:
    # Building
    build: scons
    debug: scons kernel-debug
    release: scons kernel-release
    # Testing
    test:
      script:
        - scons tests
        - ./Distribution/Tests/tests
    # Documentation
    docs: scons docs
    # Cleaning
    clean: scons -c
    clean-tests: scons -c tests
    clean-docs: scons -c docs
