image: docker.pkg.github.com/panix-os/panixbuild/panixbuild:3.2.0

aliases:
    # Building
    build: make -j$(nproc)
    debug: make -j$(nproc) debug
    release: make -j$(nproc) release
    # Testing
    test:
      script:
        - make -j$(nproc) unit-test
        - ./dist/unit-test
    # Cleaning
    clean: make clean
    test-clean: make clean-tests
    # Distribution
    image: make dist
    img:
      environment:
        IMGTYPE: img
      script: make dist
    iso:
      environment:
        IMGTYPE: iso
      script: make dist
    # Running
    run:
      environment:
        MODE: debug
      script: make run
    run-debug:
      environment:
        MODE: debug
      script:
        - make run-debug &
        - i686-elf-gdb -x gdb.commands
    run-release:
      environment:
        MODE: release
      script: make run
