name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/panix-os/panix/panixbuild:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: make dist/panix.img
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: os-image
        path: dist/panix.img
