name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kevincharm/i686-elf-gcc-toolchain
    steps:
    - name: make
      run: make
