name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xyrisos/xyris-build/xyris-build:3.5.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    # Debug
    - name: 'Build Kernel (Debug)'
      run: scons kernel-debug
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: i686-debug-xyris.img
        path: Distribution/i686/Debug/xyris.img
    # Release
    - name: 'Build Kernel (Release)'
      run: scons kernel-release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: i686-release-xyris.img
        path: Distribution/i686/Release/xyris.img
    # Unit Tests
    - name: Build and Run Tests
      run: scons tests && ./Distribution/Tests/tests -r junit --out Tests/report.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        fail_on_failure: true
        report_paths: 'Tests/report.xml'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: tests-report
        path: Tests/report.xml
