name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: docker.pkg.github.com/panix-os/panix/panixbuild:3.0.0

    steps:
    - name: make
      run: make
